### ISSUE TITLE
Deploy to npm.js

### ISSUE THREAD

**Issue by rgladwell** [textlint/grunt-textlint#1]
Would it be possible to deploy this plugin to the npm.js package repo?

**Comment by azu** [comment]
@nakajmg Is there any chance to publish?
It is needed to update [dependencies](https://github.com/textlint/grunt-textlint/blob/0fe23aade06dd2cfe23126b33ccd078e58c43287/package.json#L17) too, I think.

**Comment by nakajmg** [comment]
@rgladwell @azu 

Sorry I totally forgot this :sweat_drops: 

Now I updated dependencies & published to npm :sparkles: 
https://www.npmjs.com/package/grunt-textlint

Thanks for reminding me :pray:

**Comment by azu** [comment]
@nakajmg Thanks :+1: 

I'll close this issue.

**Comment by rgladwell** [comment]
@nakajmg thanks
